CREATE ROLE developer WITH LOGIN PASSWORD '1234';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO developer;

CREATE ROLE analista_dados;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO analista_dados;

CREATE ROLE user_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO user_app;